### ISSUE TITLE
Incorrect values for VS and HDG

### ISSUE THREAD

**Issue by carmichaelalonso** [LiveFlightApp/Connect-Windows#3] opened 2016-01-18 20:00 UTC
Some users report that VS's are reported incorrectly, usually an extremely large number (>5 digits). This also impacts AutoNav (@AR-AR-AR), where values are too high causing stalls and the such.

Not sure if this has anything to do with localisation/different decimal forms, etc?

**Comment by AR-AR-AR** [comment] 2016-01-24 02:44
Only seen one report of this so far. Unable to reproduce with different locale settings and different configurations in IF. User reported issue when AutoNav was not controlling VS, so potentially is an issue in IF itself or operator error. Will monitor for future reports.

**Comment by AR-AR-AR** [comment] 2016-02-15 00:38
By changing number settings in Windows to Turkish, was able to reproduce. Seems it really is an issue with number formatting for different locales. Will work on a fix.

**Comment by AR-AR-AR** [comment] 2016-02-15 01:04
Fixed in latest commit by adding InvariantCulture provider to the ToString for all AutoPilot setting commands in AutoNav. Also included this in the ToString in the VS calculation in the main loop in MainWindow.

Fixed in commit: https://github.com/LiveFlightApp/Connect-Windows/commit/97667c24928cdddb93412e56d08c7a616e724770

**Closed as completed by AR-AR-AR** 2016-02-15 01:04 UTC
Labels: bug
